var number=0;
module.exports = {
selector: function(number) {
if(number===0){return "阿富汗";}
else if(number===1){return "奧蘭群島";}
else if(number===2){return "阿爾巴尼亞";}
else if(number===3){return "阿爾及利亞";}
else if(number===4){return "美屬薩摩亞";}
else if(number===5){return "安道爾";}
else if(number===6){return "安哥拉";}
else if(number===7){return "安圭拉";}
else if(number===8){return "安地卡及巴布達";}
else if(number===9){return "阿根廷";}
else if(number===10){return "亞美尼亞";}
else if(number===11){return "阿魯巴";}
else if(number===12){return "澳大利亞";}
else if(number===13){return "奧地利";}
else if(number===14){return "阿塞拜疆";}
else if(number===15){return "巴哈馬";}
else if(number===16){return "巴林";}
else if(number===17){return "孟加拉國";}
else if(number===18){return "巴貝多";}
else if(number===19){return "白俄羅斯";}
else if(number===20){return "比利時";}
else if(number===21){return "貝里斯";}
else if(number===22){return "貝南";}
else if(number===23){return "百慕達";}
else if(number===24){return "不丹";}
else if(number===25){return "玻利維亞";}
else if(number===26){return "波士尼亞與赫塞哥維納";}
else if(number===27){return "波札那";}
else if(number===28){return "巴西";}
else if(number===29){return "英屬維京群島";}
else if(number===30){return "汶萊";}
else if(number===31){return "保加利亞";}
else if(number===32){return "布吉納法索";}
else if(number===33){return "緬甸";}
else if(number===34){return "蒲隆地";}
else if(number===35){return "柬埔寨";}
else if(number===36){return "喀麥隆";}
else if(number===37){return "新喀里多尼亞";}
else if(number===38){return "加拿大";}
else if(number===39){return "維德角";}
else if(number===40){return "開曼群島";}
else if(number===41){return "中非共和國";}
else if(number===42){return "查德";}
else if(number===43){return "智利";}
else if(number===44){return "聖誕島";}
else if(number===45){return "中國";}
else if(number===46){return "哥倫比亞";}
else if(number===47){return "葛摩";}
else if(number===48){return "剛果民主共和國";}
else if(number===49){return "剛果共和國";}
else if(number===50){return "庫克群島";}
else if(number===51){return "象牙海岸";}
else if(number===52){return "哥斯大黎加";}
else if(number===53){return "科科斯群島";}
else if(number===54){return "克羅埃西亞";}
else if(number===55){return "庫拉索";}
else if(number===56){return "古巴";}
else if(number===57){return "賽普勒斯";}
else if(number===58){return "捷克";}
else if(number===59){return "丹麥";}
else if(number===60){return "吉布提";}
else if(number===61){return "多米尼克";}
else if(number===62){return "多明尼加";}
else if(number===63){return "東帝汶";}
else if(number===64){return "厄瓜多";}
else if(number===65){return "埃及";}
else if(number===66){return "薩爾瓦多";}
else if(number===67){return "赤道幾內亞";}
else if(number===68){return "厄利垂亞";}
else if(number===69){return "英格蘭";}
else if(number===70){return "愛沙尼亞";}
else if(number===71){return "歐盟";}
else if(number===72){return "衣索比亞";}
else if(number===73){return "法羅群島";}
else if(number===74){return "斐濟";}
else if(number===75){return "芬蘭";}
else if(number===76){return "聖赫倫那";}
else if(number===77){return "法國";}
else if(number===78){return "法屬圭亞那";}
else if(number===79){return "法屬波利尼西亞";}
else if(number===80){return "加彭";}
else if(number===81){return "甘比亞";}
else if(number===82){return "喬治亞";}
else if(number===83){return "德國";}
else if(number===84){return "迦納";}
else if(number===85){return "直布羅陀";}
else if(number===86){return "希臘";}
else if(number===87){return "格陵蘭";}
else if(number===88){return "格瑞那達";}
else if(number===89){return "瓜地洛普";}
else if(number===90){return "關島";}
else if(number===91){return "瓜地馬拉";}
else if(number===92){return "根息";}
else if(number===93){return "幾內亞";}
else if(number===94){return "幾內亞比索";}
else if(number===95){return "圭亞那";}
else if(number===96){return "海地";}
else if(number===97){return "洪都拉斯";}
else if(number===98){return "香港";}
else if(number===99){return "匈牙利";}
else if(number===100){return "冰島";}
else if(number===101){return "印度";}
else if(number===102){return "印度尼西亞";}
else if(number===103){return "伊朗";}
else if(number===104){return "伊拉克";}
else if(number===105){return "愛爾蘭";}
else if(number===106){return "曼島";}
else if(number===107){return "以色列";}
else if(number===108){return "義大利";}
else if(number===109){return "牙買加";}
else if(number===110){return "日本";}
else if(number===111){return "澤西島";}
else if(number===112){return "約旦";}
else if(number===113){return "哈薩克";}
else if(number===114){return "肯亞";}
else if(number===115){return "吉里巴斯";}
else if(number===116){return "北韓";}
else if(number===117){return "南韓";}
else if(number===118){return "科沃索";}
else if(number===119){return "科威特";}
else if(number===120){return "吉爾吉斯";}
else if(number===121){return "寮國";}
else if(number===122){return "拉脫維亞";}
else if(number===123){return "黎巴嫩";}
else if(number===124){return "賴索托";}
else if(number===125){return "賴比瑞亞";}
else if(number===126){return "利比亞";}
else if(number===127){return "列支敦士登";}
else if(number===128){return "立陶宛";}
else if(number===129){return "盧森堡";}
else if(number===130){return "荷屬聖馬丁";}
else if(number===131){return "澳門";}
else if(number===132){return "馬其頓";}
else if(number===133){return "馬達加斯加";}
else if(number===134){return "馬拉威";}
else if(number===135){return "馬來西亞";}
else if(number===136){return "馬爾地夫";}
else if(number===137){return "馬利";}
else if(number===138){return "馬爾他";}
else if(number===139){return "馬紹爾群島";}
else if(number===140){return "馬丁尼克";}
else if(number===141){return "毛里塔尼亞";}
else if(number===142){return "模里西斯";}
else if(number===143){return "馬約特島";}
else if(number===144){return "墨西哥";}
else if(number===145){return "密克羅尼西亞";}
else if(number===146){return "摩爾多瓦";}
else if(number===147){return "摩納哥";}
else if(number===148){return "蒙古";}
else if(number===149){return "蒙哲臘";}
else if(number===150){return "蒙特內哥羅";}
else if(number===151){return "摩洛哥";}
else if(number===152){return "莫三比克";}
else if(number===153){return "納米比亞";}
else if(number===154){return "諾魯";}
else if(number===155){return "尼泊爾";}
else if(number===156){return "荷蘭";}
else if(number===157){return "荷屬安地列斯";}
else if(number===158){return "紐西蘭";}
else if(number===159){return "尼加拉瓜";}
else if(number===160){return "尼日";}
else if(number===161){return "奈及利亞";}
else if(number===162){return "紐埃";}
else if(number===163){return "北馬里亞納群島";}
else if(number===164){return "挪威";}
else if(number===165){return "巴勒斯坦";}
else if(number===166){return "阿曼";}
else if(number===167){return "巴基斯坦";}
else if(number===168){return "帛琉";}
else if(number===169){return "巴拿馬";}
else if(number===170){return "巴布亞紐幾內亞";}
else if(number===171){return "巴拉圭";}
else if(number===172){return "秘魯";}
else if(number===173){return "菲律賓";}
else if(number===174){return "波蘭";}
else if(number===175){return "聖皮埃與密克隆群島";}
else if(number===176){return "法屬玻里尼西亞";}
else if(number===177){return "葡萄牙";}
else if(number===178){return "波多黎各";}
else if(number===179){return "卡達";}
else if(number===180){return "留尼旺";}
else if(number===181){return "羅馬尼亞";}
else if(number===182){return "俄羅斯";}
else if(number===183){return "盧安達";}
else if(number===184){return "聖克里斯多福及尼維斯";}
else if(number===185){return "聖盧西亞";}
else if(number===186){return "聖文森及格瑞那丁";}
else if(number===187){return "薩摩亞";}
else if(number===188){return "聖馬利諾";}
else if(number===189){return "聖多美和普林西比";}
else if(number===190){return "沙烏地阿拉伯";}
else if(number===191){return "蘇格蘭";}
else if(number===192){return "塞內加爾";}
else if(number===193){return "塞爾維亞";}
else if(number===194){return "塞席爾";}
else if(number===195){return "獅子山";}
else if(number===196){return "新加坡";}
else if(number===197){return "斯洛伐克";}
else if(number===198){return "斯洛維尼亞";}
else if(number===199){return "所羅門群島";}
else if(number===200){return "索馬利亞";}
else if(number===201){return "南蘇丹";}
else if(number===202){return "南非";}
else if(number===203){return "西班牙";}
else if(number===204){return "斯里蘭卡";}
else if(number===205){return "蘇丹";}
else if(number===206){return "蘇利南";}
else if(number===207){return "史瓦帝尼";}
else if(number===208){return "瑞典";}
else if(number===209){return "瑞士";}
else if(number===210){return "敘利亞";}
else if(number===211){return "台灣";}
else if(number===212){return "塔吉克";}
else if(number===213){return "坦尚尼亞";}
else if(number===214){return "泰國";}
else if(number===215){return "托克勞";}
else if(number===216){return "多哥";}
else if(number===217){return "東加";}
else if(number===218){return "千里達及托巴哥";}
else if(number===219){return "突尼西亞";}
else if(number===220){return "土耳其";}
else if(number===221){return "土庫曼";}
else if(number===222){return "土克斯及開科斯群島";}
else if(number===223){return "圖瓦盧";}
else if(number===224){return "烏干達";}
else if(number===225){return "烏克蘭";}
else if(number===226){return "阿拉伯聯合大公國";}
else if(number===227){return "英國";}
else if(number===228){return "美國";}
else if(number===229){return "烏拉圭";}
else if(number===230){return "烏茲別克";}
else if(number===231){return "萬那杜";}
else if(number===232){return "梵蒂岡";}
else if(number===233){return "委內瑞拉";}
else if(number===234){return "越南";}
else if(number===235){return "瓦利斯和富圖納群島";}
else if(number===236){return "威爾斯";}
else if(number===237){return "葉門";}
else if(number===238){return "贊比亞";}
else if(number===239){return "津巴布韋";}
else if(number===240){return "聯合國";}
else if(number===241){return "魁北克";}
else if(number===242){return "北賽普勒斯";}
else if(number===243){return "聶斯特河沿岸";}
else if(number===244){return "阿布哈茲";}
else if(number===245){return "北愛爾蘭";}
else if(number===246){return "索馬利蘭";}
else if(number===247){return "頓內次克人民共和國";}
else if(number===248){return "盧干斯克人民共和國";}
else if(number===249){return "阿爾札赫";}
else if(number===250){return "南奧塞提亞";}
else if(number===251){return "西撒拉威";}
else if(number===252){return "馬爾他騎士團";}
else if(number===253){return "美屬維京群島";}
else if(number===254){return "諾福克島";}
else if(number===255){return "休達";}
else if(number===256){return "梅利利亞";}
else if(number===257){return "華盛頓哥倫比亞特區";}
}}