
var value=''; var analysis='';var output='';
module.exports = {
changer: function(value) {

        if(value==="a"){return "A";}
		else if(value==="ai"){return "AI";}
		else if(value==="an"){return "AN";}
		else if(value==="ang"){return "ANG";}
		else if(value==="ao"){return "AO";}
		else if(value==="ba"){return "PA";}
		else if(value==="bai"){return "PAI";}
		else if(value==="ban"){return "PAN";}
		else if(value==="bang"){return "PANG";}
		else if(value==="bao"){return "PAO";}
		else if(value==="bei"){return "PEI";}
		else if(value==="ben"){return "PEN";}
		else if(value==="beng"){return "PENG";}
		else if(value==="bi"){return "PI";}
		else if(value==="bian"){return "PIEN";}
		else if(value==="biao"){return "PIAO";}
		else if(value==="bie"){return "PIEH";}
		else if(value==="bin"){return "PIN";}
		else if(value==="bing"){return "PING";}
		else if(value==="bo"){return "PO";}
		else if(value==="bu"){return "PU";}
		else if(value==="ca"){return "TSA";}
		else if(value==="cai"){return "TSAI";}
		else if(value==="can"){return "TSAN";}
		else if(value==="cang"){return "TSANG";}
		else if(value==="cao"){return "TSA";}
		else if(value==="ce"){return "TSE";}
		else if(value==="cen"){return "TSEN";}
		else if(value==="ceng"){return "TSENG";}
		else if(value==="cha"){return "CHA";}
		else if(value==="chai"){return "CHAI";}
		else if(value==="chan"){return "CHAN";}
		else if(value==="chang"){return "CHANG";}
		else if(value==="chao"){return "CHAO";}
		else if(value==="che"){return "CHE";}
		else if(value==="chen"){return "CHEN";}
		else if(value==="cheng"){return "CHENG";}
		else if(value==="chi"){return "CHIH";}
		else if(value==="chong"){return "CHUNG";}
		else if(value==="chou"){return "CHOU";}
		else if(value==="chu"){return "CHU";}
		else if(value==="chua"){return "CHUA";}
		else if(value==="chuai"){return "CHUAI";}
		else if(value==="chuan"){return "CHUAN";}
		else if(value==="chuang"){return "CHUANG";}
		else if(value==="chui"){return "CHUI";}
		else if(value==="chun"){return "CHUN";}
		else if(value==="chuo"){return "CHO";}
		else if(value==="ci"){return "TZU";}
		else if(value==="cong"){return "TSUNG";}
		else if(value==="cou"){return "TSOU";}
		else if(value==="cu"){return "TSU";}
		else if(value==="cuan"){return "TSUAN";}
		else if(value==="cui"){return "TSUI";}
		else if(value==="cun"){return "TSUN";}
		else if(value==="cuo"){return "TSO";}
		else if(value==="da"){return "TA";}
		else if(value==="dai"){return "TAI";}
		else if(value==="dan"){return "TAN";}
		else if(value==="dang"){return "TANG";}
		else if(value==="dao"){return "TAO";}
		else if(value==="de"){return "TE";}
		else if(value==="dei"){return "TEI";}
		else if(value==="den"){return "TEI";}
		else if(value==="deng"){return "TENG";}
		else if(value==="di"){return "TI";}
		else if(value==="dia"){return "TIA";}
		else if(value==="dian"){return "TIEN";}
		else if(value==="diao"){return "TIAO";}
		else if(value==="die"){return "TIEH";}
		else if(value==="ding"){return "TING";}
		else if(value==="diu"){return "TIU";}
		else if(value==="dong"){return "TUNG";}
		else if(value==="dou"){return "TOU";}
		else if(value==="du"){return "TU";}
		else if(value==="duan"){return "TUAN";}
		else if(value==="dui"){return "TUI";}
		else if(value==="dun"){return "TUN";}
		else if(value==="duo"){return "TO";}
		else if(value==="e"){return "E";}
		else if(value==="ei"){return "EI";}
		else if(value==="en"){return "EN";}
		else if(value==="eng"){return "ENG";}
		else if(value==="er"){return "ERH";}
		else if(value==="fa"){return "FA";}
		else if(value==="fan"){return "FAN";}
		else if(value==="fang"){return "FANG";}
		else if(value==="fei"){return "FEI";}
		else if(value==="fen"){return "FEN";}
		else if(value==="feng"){return "FENG";}
		else if(value==="fo"){return "FO";}
		else if(value==="fou"){return "FOU";}
		else if(value==="fu"){return "FU";}
		else if(value==="ga"){return "KA";}
		else if(value==="gai"){return "KAI";}
		else if(value==="gan"){return "KAN";}
		else if(value==="gang"){return "KANG";}
		else if(value==="gao"){return "KAO";}
		else if(value==="ge"){return "KE";}
		else if(value==="gei"){return "KEI";}
		else if(value==="gen"){return "KEN";}
		else if(value==="geng"){return "KENG";}
		else if(value==="gong"){return "KUNG";}
		else if(value==="gou"){return "KOU";}
		else if(value==="gu"){return "KU";}
		else if(value==="gua"){return "KUA";}
		else if(value==="guai"){return "KUAI";}
		else if(value==="guan"){return "KUAN";}
		else if(value==="guang"){return "KUANG";}
		else if(value==="gui"){return "KUEI";}
		else if(value==="gun"){return "KUN";}
		else if(value==="guo"){return "KUO";}
		else if(value==="ha"){return "HA";}
		else if(value==="hai"){return "HAI";}
		else if(value==="han"){return "HAN";}
		else if(value==="hang"){return "HANG";}
		else if(value==="hao"){return "HAO";}
		else if(value==="he"){return "HE";}
		else if(value==="hei"){return "HEI";}
		else if(value==="hen"){return "HEN";}
		else if(value==="heng"){return "HENG";}
		else if(value==="hong"){return "HUNG";}
		else if(value==="hou"){return "HOU";}
		else if(value==="hu"){return "HU";}
		else if(value==="hua"){return "HUA";}
		else if(value==="huai"){return "HUAI";}
		else if(value==="huan"){return "HUAN";}
		else if(value==="huang"){return "HUANG";}
		else if(value==="hui"){return "HUI";}
		else if(value==="hun"){return "HUN";}
		else if(value==="huo"){return "HUO";}
		else if(value==="ji"){return "CHI";}
		else if(value==="jia"){return "CHIA";}
		else if(value==="jian"){return "CHIEN";}
		else if(value==="jiang"){return "CHIANG";}
		else if(value==="jiao"){return "CHIAO";}
		else if(value==="jie"){return "CHIEH";}
		else if(value==="jin"){return "CHIN";}
		else if(value==="jing"){return "CHING";}
		else if(value==="jiong"){return "CHIUNG";}
		else if(value==="jiu"){return "CHIU";}
		else if(value==="ju"){return "CHU";}
		else if(value==="juan"){return "CHUAN";}
		else if(value==="jue"){return "CHUAN";}
		else if(value==="jun"){return "CHUN";}
		else if(value==="ka"){return "KA";}
		else if(value==="kai"){return "KAI";}
		else if(value==="kan"){return "KAN";}
		else if(value==="kang"){return "KANG";}
		else if(value==="kao"){return "KAO";}
		else if(value==="ke"){return "KO";}
		else if(value==="kei"){return "KE";}
		else if(value==="ken"){return "KEN";}
		else if(value==="keng"){return "KENG";}
		else if(value==="kong"){return "KUNG";}
		else if(value==="kou"){return "KOU";}
		else if(value==="ku"){return "KU";}
		else if(value==="kua"){return "KUA";}
		else if(value==="kuai"){return "KUAI";}
		else if(value==="kuan"){return "KUAN";}
		else if(value==="kuang"){return "KUANG";}
		else if(value==="kui"){return "KUEI";}
		else if(value==="kun"){return "KUN";}
		else if(value==="kuo"){return "KUO";}
		else if(value==="la"){return "LA";}
		else if(value==="lai"){return "LAI";}
		else if(value==="lan"){return "LAN";}
		else if(value==="lang"){return "LANG";}
		else if(value==="lao"){return "LAO";}
		else if(value==="le"){return "LE";}
		else if(value==="lei"){return "LEI";}
		else if(value==="leng"){return "LENG";}
		else if(value==="li"){return "LI";}
		else if(value==="lia"){return "LIA";}
		else if(value==="lian"){return "LIEN";}
		else if(value==="liang"){return "LIANG";}
		else if(value==="liao"){return "LIEH";}
		else if(value==="lie"){return "LIEH";}
		else if(value==="lin"){return "LIN";}
		else if(value==="ling"){return "LING";}
		else if(value==="liu"){return "LIU";}
		else if(value==="long"){return "LUNG";}
		else if(value==="lou"){return "LOU";}
		else if(value==="lu"){return "LU";}
		else if(value==="lü"){return "LU";}
		else if(value==="luan"){return "LUAN";}
		else if(value==="lüe"){return "LUEH";}
		else if(value==="lun"){return "LUN";}
		else if(value==="luo"){return "LO";}
		else if(value==="ma"){return "MA";}
		else if(value==="mai"){return "MAI";}
		else if(value==="man"){return "MAN";}
		else if(value==="mang"){return "MANG";}
		else if(value==="mao"){return "MAO";}
		else if(value==="me"){return "ME";}
		else if(value==="mei"){return "MEI";}
		else if(value==="men"){return "MEN";}
		else if(value==="meng"){return "MENG";}
		else if(value==="mi"){return "MI";}
		else if(value==="mian"){return "MIEN";}
		else if(value==="miao"){return "MIAO";}
		else if(value==="mie"){return "MIEH";}
		else if(value==="min"){return "MIN";}
		else if(value==="ming"){return "MING";}
		else if(value==="miu"){return "MIU";}
		else if(value==="mo"){return "MO";}
		else if(value==="mou"){return "MOU";}
		else if(value==="mu"){return "MU";}
		else if(value==="na"){return "NA";}
		else if(value==="nai"){return "NAI";}
		else if(value==="nan"){return "NAN";}
		else if(value==="nang"){return "NANG";}
		else if(value==="nao"){return "NAO";}
		else if(value==="ne"){return "NE";}
		else if(value==="nei"){return "NEI";}
		else if(value==="nen"){return "NEN";}
		else if(value==="neng"){return "NENG";}
		else if(value==="ni"){return "NI";}
		else if(value==="nian"){return "NIEN";}
		else if(value==="niang"){return "NIANG";}
		else if(value==="niao"){return "NIAO";}
		else if(value==="nie"){return "NIEH";}
		else if(value==="nin"){return "NIN";}
		else if(value==="ning"){return "NING";}
		else if(value==="niu"){return "NIU";}
		else if(value==="nong"){return "NUNG";}
		else if(value==="nou"){return "NOU";}
		else if(value==="nu"){return "NU";}
		else if(value==="nü"){return "NU";}
		else if(value==="nuan"){return "NUAN";}
		else if(value==="nüe"){return "NUEH";}
		else if(value==="nun"){return "NUNG";}
		else if(value==="nuo"){return "NO";}
		else if(value==="o"){return "O";}
		else if(value==="ou"){return "OU";}
		else if(value==="pa"){return "PA";}
		else if(value==="pai"){return "PAI";}
		else if(value==="pan"){return "PAN";}
		else if(value==="pang"){return "PANG";}
		else if(value==="pao"){return "PAO";}
		else if(value==="pei"){return "PEI";}
		else if(value==="pen"){return "PEN";}
		else if(value==="peng"){return "PENG";}
		else if(value==="pi"){return "PI";}
		else if(value==="pian"){return "PIEN";}
		else if(value==="piao"){return "PIAO";}
		else if(value==="pie"){return "PIEH";}
		else if(value==="pin"){return "PIN";}
		else if(value==="ping"){return "PING";}
		else if(value==="po"){return "PO";}
		else if(value==="pou"){return "POU";}
		else if(value==="pu"){return "PU";}
		else if(value==="qi"){return "CHI";}
		else if(value==="qia"){return "CHIA";}
		else if(value==="qian"){return "CHIEN";}
		else if(value==="qiang"){return "CHIANG";}
		else if(value==="qiao"){return "CHIAO";}
		else if(value==="qie"){return "CHIEH";}
		else if(value==="qin"){return "CHIN";}
		else if(value==="qing"){return "CHING";}
		else if(value==="qiong"){return "CHIUNG";}
		else if(value==="qiu"){return "CHIU'";}
		else if(value==="qu"){return "CHU";}
		else if(value==="quan"){return "CHUAN";}
		else if(value==="que"){return "CHUEH";}
		else if(value==="qun"){return "CHUN";}
		else if(value==="ran"){return "JAN";}
		else if(value==="rang"){return "JANG";}
		else if(value==="rao"){return "JAO";}
		else if(value==="re"){return "JE'";}
		else if(value==="ren"){return "JEN";}
		else if(value==="reng"){return "JENG";}
		else if(value==="ri"){return "JIH";}
		else if(value==="rong"){return "JUNG";}
		else if(value==="rou"){return "JOU";}
		else if(value==="ru"){return "JUNG";}
		else if(value==="rua"){return "JUA";}
		else if(value==="ruan"){return "JUAN";}
		else if(value==="rui"){return "JUI";}
		else if(value==="run"){return "JUN";}
		else if(value==="ruo"){return "JO";}
		else if(value==="sa"){return "SA";}
		else if(value==="sai"){return "SAI";}
		else if(value==="san"){return "SAN";}
		else if(value==="sang"){return "SANG";}
		else if(value==="sao"){return "SAO";}
		else if(value==="se"){return "SE";}
		else if(value==="sen"){return "SEN";}
		else if(value==="seng"){return "SENG";}
		else if(value==="sha"){return "SHA";}
		else if(value==="shai"){return "SHAI";}
		else if(value==="shan"){return "SHAN";}
		else if(value==="shang"){return "SHANG";}
		else if(value==="shao"){return "SHAO";}
		else if(value==="she"){return "SHE";}
		else if(value==="shei"){return "SHEI";}
		else if(value==="shen"){return "SHEN";}
		else if(value==="sheng"){return "SHENG";}
		else if(value==="shi"){return "SHIH";}
		else if(value==="shou"){return "SHOU";}
		else if(value==="shu"){return "SHU";}
		else if(value==="shua"){return "SHUA";}
		else if(value==="shuai"){return "SHUAI";}
		else if(value==="shuan"){return "SHUAN";}
		else if(value==="shuang"){return "SHUANG";}
		else if(value==="shui"){return "SHUI";}
		else if(value==="shun"){return "SHUN";}
		else if(value==="shuo"){return "SHUO";}
		else if(value==="si"){return "SSU";}
		else if(value==="song"){return "SUNG";}
		else if(value==="sou"){return "SOU";}
		else if(value==="su"){return "SU";}
		else if(value==="suan"){return "SUAN";}
		else if(value==="sui"){return "SUI";}
		else if(value==="sun"){return "SUN";}
		else if(value==="suo"){return "SO";}
		else if(value==="ta"){return "TA";}
		else if(value==="tai"){return "TAI";}
		else if(value==="tan"){return "TAN";}
		else if(value==="tang"){return "TANG";}
		else if(value==="tao"){return "TAO";}
		else if(value==="te"){return "TE";}
		else if(value==="tei"){return "TE";}
		else if(value==="teng"){return "TENG";}
		else if(value==="ti"){return "TI";}
		else if(value==="tian"){return "TIEN";}
		else if(value==="tiao"){return "TIAO";}
		else if(value==="tie"){return "TIEH";}
		else if(value==="ting"){return "TING";}
		else if(value==="tong"){return "TUNG";}
		else if(value==="tou"){return "TOU";}
		else if(value==="tu"){return "TU";}
		else if(value==="tuan"){return "TUAN";}
		else if(value==="tui"){return "TUI";}
		else if(value==="tun"){return "TUN'";}
		else if(value==="tuo"){return "TO";}
		else if(value==="wa"){return "WA";}
		else if(value==="wai"){return "WAI";}
		else if(value==="wan"){return "WAN";}
		else if(value==="wang"){return "WAN";}
		else if(value==="wei"){return "WEI";}
		else if(value==="wen"){return "WEN";}
		else if(value==="weng"){return "WENG";}
		else if(value==="wo"){return "WO";}
		else if(value==="wu"){return "WU";}
		else if(value==="xi"){return "HSI";}
		else if(value==="xia"){return "HSIA";}
		else if(value==="xian"){return "HSIEN";}
		else if(value==="xiang"){return "HSIANG";}
		else if(value==="xiao"){return "HSIAO";}
		else if(value==="xie"){return "HSIEH";}
		else if(value==="xin"){return "HSIN";}
		else if(value==="xing"){return "HSING";}
		else if(value==="xiong"){return "HSIUNG";}
		else if(value==="xiu"){return "HSIU";}
		else if(value==="xu"){return "HSU";}
		else if(value==="xuan"){return "HSUAN";}
		else if(value==="xue"){return "HSUEH";}
		else if(value==="xun"){return "HSUN";}
		else if(value==="ya"){return "YA";}
		else if(value==="yan"){return "YEN";}
		else if(value==="yang"){return "YANG";}
		else if(value==="yao"){return "YAO";}
		else if(value==="yai"){return "YAI";}
		else if(value==="ye"){return "YEH";}
		else if(value==="yi"){return "YI";}
		else if(value==="yin"){return "YIN";}
		else if(value==="ying"){return "YING";}
		else if(value==="yong"){return "YUNG";}
		else if(value==="yo"){return "YO";}
		else if(value==="you"){return "YU";}
		else if(value==="yu"){return "YU";}
		else if(value==="yuan"){return "YUAN";}
		else if(value==="yue"){return "'YUEH";}
		else if(value==="yun"){return "YUN";}
		else if(value==="za"){return "TSA";}
		else if(value==="zai"){return "TSAI";}
		else if(value==="zan"){return "TSAN";}
		else if(value==="zang"){return "TSANG";}
		else if(value==="zao"){return "TSAO";}
		else if(value==="ze"){return "TSE";}
		else if(value==="zei"){return "TSEI";}
		else if(value==="zen"){return "TSEN";}
		else if(value==="zeng"){return "TSENG";}
		else if(value==="zha"){return "CHA";}
		else if(value==="zhai"){return "CHAI";}
		else if(value==="zhan"){return "CHAN";}
		else if(value==="zhang"){return "CHANG";}
		else if(value==="zhao"){return "CHAO";}
		else if(value==="zhe"){return "CHE";}
		else if(value==="zhei"){return "CHEI";}
		else if(value==="zhen"){return "CHEN";}
		else if(value==="zheng"){return "CHENG";}
		else if(value==="zhi"){return "CHIH";}
		else if(value==="zhong"){return "CHUNG";}
		else if(value==="zhou"){return "CHOU";}
		else if(value==="zhu"){return "CHU";}
		else if(value==="zhua"){return "CHUA";}
		else if(value==="zhuai"){return "CHUAI";}
		else if(value==="zhuan"){return "CHUAN";}
		else if(value==="zhuang"){return "CHUANG";}
		else if(value==="zhui"){return "CHUI";}
		else if(value==="zhun"){return "CHUN";}
		else if(value==="zhuo"){return "CHO";}
		else if(value==="zi"){return "TZU";}
		else if(value==="zong"){return "TSUNG";}
		else if(value==="zou"){return "TSOU";}
		else if(value==="zu"){return "TSU";}
		else if(value==="zuan"){return "TSUAN";}
		else if(value==="zui"){return "TSUI";}
		else if(value==="zun"){return "TSUN";}
		else if(value==="zuo"){return "TSO";}
		
		}}