var zipcode='';
module.exports = {
table: function(zipcode) {

if (zipcode==="100"){return "臺北市 中正區"}
else if (zipcode==="103"){return "臺北市 大同區"}
else if (zipcode==="104"){return "臺北市 中山區"}
else if (zipcode==="105"){return "臺北市 松山區"}
else if (zipcode==="106"){return "臺北市 大安區"}
else if (zipcode==="108"){return "臺北市 萬華區"}
else if (zipcode==="110"){return "臺北市 信義區"}
else if (zipcode==="111"){return "臺北市 士林區"}
else if (zipcode==="112"){return "臺北市 北投區"}
else if (zipcode==="114"){return "臺北市 內湖區"}
else if (zipcode==="115"){return "臺北市 南港區"}
else if (zipcode==="116"){return "臺北市 文山區"}

else if (zipcode==="200"){return "基隆市 仁愛區"}
else if (zipcode==="201"){return "基隆市 信義區"}
else if (zipcode==="202"){return "基隆市 中正區"}
else if (zipcode==="203"){return "基隆市 中山區"}
else if (zipcode==="204"){return "基隆市 安樂區"}
else if (zipcode==="205"){return "基隆市 暖暖區"}
else if (zipcode==="206"){return "基隆市 七堵區"}

else if (zipcode==="207"){return "新北市 萬里區"}
else if (zipcode==="208"){return "新北市 金山區"}
else if (zipcode==="220"){return "新北市 板橋區"}
else if (zipcode==="221"){return "新北市 汐止區"}
else if (zipcode==="222"){return "新北市 深坑區"}
else if (zipcode==="223"){return "新北市 石碇區"}
else if (zipcode==="224"){return "新北市 瑞芳區"}
else if (zipcode==="226"){return "新北市 平溪區"}
else if (zipcode==="227"){return "新北市 雙溪區"}
else if (zipcode==="228"){return "新北市 貢寮區"}
else if (zipcode==="231"){return "新北市 新店區"}
else if (zipcode==="232"){return "新北市 坪林區"}
else if (zipcode==="233"){return "新北市 烏來區"}
else if (zipcode==="234"){return "新北市 永和區"}
else if (zipcode==="235"){return "新北市 中和區"}
else if (zipcode==="236"){return "新北市 土城區"}
else if (zipcode==="237"){return "新北市 三峽區"}
else if (zipcode==="238"){return "新北市 樹林區"}
else if (zipcode==="239"){return "新北市 鶯歌區"}
else if (zipcode==="241"){return "新北市 三重區"}
else if (zipcode==="242"){return "新北市 新莊區"}
else if (zipcode==="243"){return "新北市 泰山區"}
else if (zipcode==="244"){return "新北市 林口區"}
else if (zipcode==="247"){return "新北市 蘆洲區"}
else if (zipcode==="248"){return "新北市 五股區"}
else if (zipcode==="249"){return "新北市 八里區"}
else if (zipcode==="251"){return "新北市 淡水區"}
else if (zipcode==="252"){return "新北市 三芝區"}
else if (zipcode==="253"){return "新北市 石門區"}

else if (zipcode==="260"){return "宜蘭縣 宜蘭市"}
else if (zipcode==="261"){return "宜蘭縣 頭城鄉"}
else if (zipcode==="262"){return "宜蘭縣 礁溪鄉"}
else if (zipcode==="263"){return "宜蘭縣 壯圍鄉"}
else if (zipcode==="264"){return "宜蘭縣 員山鄉"}
else if (zipcode==="265"){return "宜蘭縣 羅東鄉"}
else if (zipcode==="266"){return "宜蘭縣 三星鄉"}
else if (zipcode==="267"){return "宜蘭縣 大同鄉"}
else if (zipcode==="268"){return "宜蘭縣 五結鄉"}
else if (zipcode==="269"){return "宜蘭縣 冬山鄉"}
else if (zipcode==="270"){return "宜蘭縣 蘇澳鄉"}
else if (zipcode==="272"){return "宜蘭縣 南澳鄉"}
else if (zipcode==="290"){return "宜蘭縣 釣魚臺列嶼"}

else if (zipcode==="300"){return "新竹市"}
else if (zipcode==="302"){return "新竹縣 竹北市"}
else if (zipcode==="303"){return "新竹縣 湖口鄉"}
else if (zipcode==="304"){return "新竹縣 新豐鄉"}
else if (zipcode==="305"){return "新竹縣 新埔鎮"}
else if (zipcode==="306"){return "新竹縣 關西鎮"}
else if (zipcode==="307"){return "新竹縣 芎林鄉"}
else if (zipcode==="308"){return "新竹縣 寶山鄉"}
else if (zipcode==="310"){return "新竹縣 竹東鎮"}
else if (zipcode==="311"){return "新竹縣 五峰鄉"}
else if (zipcode==="312"){return "新竹縣 橫山鄉"}
else if (zipcode==="313"){return "新竹縣 尖石鄉"}
else if (zipcode==="314"){return "新竹縣 北埔鄉"}
else if (zipcode==="315"){return "新竹縣 峨眉鄉"}

else if (zipcode==="320"){return "桃園市 中壢區"}
else if (zipcode==="324"){return "桃園市 平鎮區"}
else if (zipcode==="325"){return "桃園市 龍潭區"}
else if (zipcode==="326"){return "桃園市 楊梅區"}
else if (zipcode==="327"){return "桃園市 新屋區"}
else if (zipcode==="328"){return "桃園市 觀音區"}
else if (zipcode==="330"){return "桃園市 桃園區"}
else if (zipcode==="333"){return "桃園市 龜山區"}
else if (zipcode==="334"){return "桃園市 八德區"}
else if (zipcode==="335"){return "桃園市 大溪區"}
else if (zipcode==="336"){return "桃園市 復興區"}
else if (zipcode==="337"){return "桃園市 大園區"}
else if (zipcode==="338"){return "桃園市 蘆竹區"}

else if (zipcode==="350"){return "苗栗縣 竹南鎮"}
else if (zipcode==="351"){return "苗栗縣 頭份市"}
else if (zipcode==="352"){return "苗栗縣 三灣鄉"}
else if (zipcode==="353"){return "苗栗縣 南庄鄉"}
else if (zipcode==="354"){return "苗栗縣 獅潭鄉"}
else if (zipcode==="356"){return "苗栗縣 後龍鎮"}
else if (zipcode==="357"){return "苗栗縣 通霄鎮"}
else if (zipcode==="358"){return "苗栗縣 苑裡鎮"}
else if (zipcode==="360"){return "苗栗縣 苗栗市"}
else if (zipcode==="361"){return "苗栗縣 造橋鄉"}
else if (zipcode==="362"){return "苗栗縣 頭屋鄉"}
else if (zipcode==="363"){return "苗栗縣 公館鄉"}
else if (zipcode==="364"){return "苗栗縣 大湖鄉"}
else if (zipcode==="365"){return "苗栗縣 泰安鄉"}
else if (zipcode==="366"){return "苗栗縣 銅鑼鄉"}
else if (zipcode==="367"){return "苗栗縣 三義鄉"}
else if (zipcode==="368"){return "苗栗縣 西湖鄉"}
else if (zipcode==="369"){return "苗栗縣 卓蘭鎮"}

else if (zipcode==="400"){return "臺中市 中區"}
else if (zipcode==="401"){return "臺中市 東區"}
else if (zipcode==="402"){return "臺中市 南區"}
else if (zipcode==="403"){return "臺中市 西區"}
else if (zipcode==="404"){return "臺中市 北區"}
else if (zipcode==="406"){return "臺中市 北屯區"}
else if (zipcode==="407"){return "臺中市 西屯區"}
else if (zipcode==="408"){return "臺中市 南屯區"}
else if (zipcode==="411"){return "臺中市 太平區"}
else if (zipcode==="412"){return "臺中市 大里區"}
else if (zipcode==="413"){return "臺中市 霧峰區"}
else if (zipcode==="414"){return "臺中市 烏日區"}
else if (zipcode==="420"){return "臺中市 豐原區"}
else if (zipcode==="421"){return "臺中市 后里區"}
else if (zipcode==="422"){return "臺中市 石岡區"}
else if (zipcode==="423"){return "臺中市 東勢區"}
else if (zipcode==="424"){return "臺中市 和平區"}
else if (zipcode==="426"){return "臺中市 新社區"}
else if (zipcode==="427"){return "臺中市 潭子區"}
else if (zipcode==="428"){return "臺中市 大雅區"}
else if (zipcode==="429"){return "臺中市 神岡區"}
else if (zipcode==="432"){return "臺中市 大肚區"}
else if (zipcode==="433"){return "臺中市 沙鹿區"}
else if (zipcode==="434"){return "臺中市 龍井區"}
else if (zipcode==="435"){return "臺中市 梧棲區"}
else if (zipcode==="436"){return "臺中市 清水區"}
else if (zipcode==="437"){return "臺中市 大甲區"}
else if (zipcode==="438"){return "臺中市 外埔區"}
else if (zipcode==="439"){return "臺中市 大安區"}

else if (zipcode==="500"){return "彰化縣 彰化市"}
else if (zipcode==="502"){return "彰化縣 芬園鄉"}
else if (zipcode==="503"){return "彰化縣 花壇鄉"}
else if (zipcode==="504"){return "彰化縣 秀水鄉"}
else if (zipcode==="505"){return "彰化縣 鹿港鎮"}
else if (zipcode==="506"){return "彰化縣 福興鄉"}
else if (zipcode==="507"){return "彰化縣 線西鄉"}
else if (zipcode==="508"){return "彰化縣 和美鎮"}
else if (zipcode==="509"){return "彰化縣 伸港鄉"}
else if (zipcode==="510"){return "彰化縣 員林市"}
else if (zipcode==="511"){return "彰化縣 社頭鄉"}
else if (zipcode==="512"){return "彰化縣 永靖鄉"}
else if (zipcode==="513"){return "彰化縣 埔心鄉"}
else if (zipcode==="514"){return "彰化縣 溪湖鎮"}
else if (zipcode==="515"){return "彰化縣 大村鄉"}
else if (zipcode==="516"){return "彰化縣 埔鹽鄉"}
else if (zipcode==="520"){return "彰化縣 田中鎮"}
else if (zipcode==="521"){return "彰化縣 北斗鎮"}
else if (zipcode==="522"){return "彰化縣 田尾鄉"}
else if (zipcode==="523"){return "彰化縣 埤頭鄉"}
else if (zipcode==="524"){return "彰化縣 溪州鄉"}
else if (zipcode==="525"){return "彰化縣 竹塘鄉"}
else if (zipcode==="526"){return "彰化縣 二林鎮"}
else if (zipcode==="527"){return "彰化縣 大城鄉"}
else if (zipcode==="528"){return "彰化縣 芳苑鄉"}
else if (zipcode==="530"){return "彰化縣 二水鄉"}

else if (zipcode==="540"){return "南投縣 南投市"}
else if (zipcode==="541"){return "南投縣 中寮鄉"}
else if (zipcode==="542"){return "南投縣 草屯鎮"}
else if (zipcode==="544"){return "南投縣 國姓鄉"}
else if (zipcode==="545"){return "南投縣 埔里鎮"}
else if (zipcode==="546"){return "南投縣 仁愛鄉"}
else if (zipcode==="551"){return "南投縣 名間鄉"}
else if (zipcode==="552"){return "南投縣 集集鎮"}
else if (zipcode==="553"){return "南投縣 水里鄉"}
else if (zipcode==="555"){return "南投縣 魚池鄉"}
else if (zipcode==="556"){return "南投縣 信義鄉"}
else if (zipcode==="557"){return "南投縣 竹山鎮"}
else if (zipcode==="558"){return "南投縣 鹿谷鄉"}
else if (zipcode==="600"){return "嘉義市"}
else if (zipcode==="602"){return "嘉義縣 番路鄉"}
else if (zipcode==="603"){return "嘉義縣 梅山鄉"}
else if (zipcode==="604"){return "嘉義縣 竹崎鄉"}
else if (zipcode==="605"){return "嘉義縣 阿里山鄉"}
else if (zipcode==="606"){return "嘉義縣 中埔鄉"}
else if (zipcode==="607"){return "嘉義縣 大埔鄉"}
else if (zipcode==="608"){return "嘉義縣 水上鄉"}
else if (zipcode==="611"){return "嘉義縣 鹿草鄉"}
else if (zipcode==="612"){return "嘉義縣 太保市"}
else if (zipcode==="613"){return "嘉義縣 朴子市"}
else if (zipcode==="614"){return "嘉義縣 東石鄉"}
else if (zipcode==="615"){return "嘉義縣 六腳鄉"}
else if (zipcode==="616"){return "嘉義縣 新港鄉"}
else if (zipcode==="621"){return "嘉義縣 民雄鄉"}
else if (zipcode==="622"){return "嘉義縣 大林鎮"}
else if (zipcode==="623"){return "嘉義縣 溪口鄉"}
else if (zipcode==="624"){return "嘉義縣 義竹鄉"}
else if (zipcode==="625"){return "嘉義縣 布袋鎮"}

else if (zipcode==="630"){return "雲林縣 斗南鎮"}
else if (zipcode==="631"){return "雲林縣 大埤鄉"}
else if (zipcode==="632"){return "雲林縣 虎尾鎮"}
else if (zipcode==="633"){return "雲林縣 土庫鎮"}
else if (zipcode==="634"){return "雲林縣 褒忠鄉"}
else if (zipcode==="635"){return "雲林縣 東勢鄉"}
else if (zipcode==="636"){return "雲林縣 臺西鄉"}
else if (zipcode==="637"){return "雲林縣 崙背鄉"}
else if (zipcode==="638"){return "雲林縣 麥寮鄉"}
else if (zipcode==="640"){return "雲林縣 斗六市"}
else if (zipcode==="643"){return "雲林縣 林內鄉"}
else if (zipcode==="646"){return "雲林縣 古坑鄉"}
else if (zipcode==="647"){return "雲林縣 莿桐鄉"}
else if (zipcode==="648"){return "雲林縣 西螺鎮"}
else if (zipcode==="649"){return "雲林縣 二崙鄉"}
else if (zipcode==="651"){return "雲林縣 北港鎮"}
else if (zipcode==="652"){return "雲林縣 水林鄉"}
else if (zipcode==="653"){return "雲林縣 口湖鄉"}
else if (zipcode==="654"){return "雲林縣 四湖鄉"}
else if (zipcode==="655"){return "雲林縣 元長鄉"}

else if (zipcode==="700"){return "臺南市 中西區"}
else if (zipcode==="701"){return "臺南市 東區"}
else if (zipcode==="702"){return "臺南市 南區"}
else if (zipcode==="704"){return "臺南市 北區"}
else if (zipcode==="708"){return "臺南市 安平區"}
else if (zipcode==="709"){return "臺南市 安南區"}
else if (zipcode==="710"){return "臺南市 永康區"}
else if (zipcode==="711"){return "臺南市 歸仁區"}
else if (zipcode==="712"){return "臺南市 新化區"}
else if (zipcode==="713"){return "臺南市 左鎮區"}
else if (zipcode==="714"){return "臺南市 玉井區"}
else if (zipcode==="715"){return "臺南市 楠西區"}
else if (zipcode==="716"){return "臺南市 南化區"}
else if (zipcode==="717"){return "臺南市 仁德區"}
else if (zipcode==="718"){return "臺南市 關廟區"}
else if (zipcode==="719"){return "臺南市 龍崎區"}
else if (zipcode==="720"){return "臺南市 官田區"}
else if (zipcode==="721"){return "臺南市 麻豆區"}
else if (zipcode==="722"){return "臺南市 佳里區"}
else if (zipcode==="723"){return "臺南市 西港區"}
else if (zipcode==="724"){return "臺南市 七股區"}
else if (zipcode==="725"){return "臺南市 將軍區"}
else if (zipcode==="726"){return "臺南市 學甲區"}
else if (zipcode==="727"){return "臺南市 北門區"}
else if (zipcode==="730"){return "臺南市 新營區"}
else if (zipcode==="731"){return "臺南市 後壁區"}
else if (zipcode==="732"){return "臺南市 白河區"}
else if (zipcode==="733"){return "臺南市 東山區"}
else if (zipcode==="734"){return "臺南市 六甲區"}
else if (zipcode==="735"){return "臺南市 下營區"}
else if (zipcode==="736"){return "臺南市 柳營區"}
else if (zipcode==="737"){return "臺南市 鹽水區"}
else if (zipcode==="741"){return "臺南市 善化區"}
else if (zipcode==="742"){return "臺南市 大內區"}
else if (zipcode==="743"){return "臺南市 山上區"}
else if (zipcode==="744"){return "臺南市 新市區"}
else if (zipcode==="745"){return "臺南市 安定區"}
else if (zipcode==="800"){return "高雄市 新興區"}
else if (zipcode==="801"){return "高雄市 前金區"}
else if (zipcode==="802"){return "高雄市 苓雅區"}
else if (zipcode==="803"){return "高雄市 鹽埕區"}
else if (zipcode==="804"){return "高雄市 鼓山區"}
else if (zipcode==="805"){return "高雄市 旗津區"}
else if (zipcode==="806"){return "高雄市 前鎮區"}
else if (zipcode==="807"){return "高雄市 三民區"}
else if (zipcode==="811"){return "高雄市 楠梓區"}
else if (zipcode==="812"){return "高雄市 小港區"}
else if (zipcode==="813"){return "高雄市 左營區"}
else if (zipcode==="814"){return "高雄市 仁武區"}
else if (zipcode==="815"){return "高雄市 大社區"}
else if (zipcode==="820"){return "高雄市 岡山區"}
else if (zipcode==="821"){return "高雄市 路竹區"}
else if (zipcode==="822"){return "高雄市 阿蓮區"}
else if (zipcode==="823"){return "高雄市 田寮區"}
else if (zipcode==="824"){return "高雄市 燕巢區"}
else if (zipcode==="825"){return "高雄市 橋頭區"}
else if (zipcode==="826"){return "高雄市 梓官區"}
else if (zipcode==="827"){return "高雄市 彌陀區"}
else if (zipcode==="828"){return "高雄市 永安區"}
else if (zipcode==="829"){return "高雄市 湖內區"}
else if (zipcode==="830"){return "高雄市 鳳山區"}
else if (zipcode==="831"){return "高雄市 大寮區"}
else if (zipcode==="832"){return "高雄市 林園區"}
else if (zipcode==="833"){return "高雄市 鳥松區"}
else if (zipcode==="840"){return "高雄市 大樹區"}
else if (zipcode==="842"){return "高雄市 旗山區"}
else if (zipcode==="843"){return "高雄市 美濃區"}
else if (zipcode==="844"){return "高雄市 六龜區"}
else if (zipcode==="845"){return "高雄市 內門區"}
else if (zipcode==="846"){return "高雄市 杉林區"}
else if (zipcode==="847"){return "高雄市 甲仙區"}
else if (zipcode==="848"){return "高雄市 桃源區"}
else if (zipcode==="849"){return "高雄市 那瑪夏區"}
else if (zipcode==="851"){return "高雄市 茂林區"}
else if (zipcode==="852"){return "高雄市 茄萣區"}
else if (zipcode==="817"){return "南海諸島	東 沙"}
else if (zipcode==="819"){return "南海諸島	南 沙"}
else if (zipcode==="880"){return "澎湖縣 馬公市"}
else if (zipcode==="881"){return "澎湖縣 西嶼鄉"}
else if (zipcode==="882"){return "澎湖縣 望安鄉"}
else if (zipcode==="883"){return "澎湖縣 七美鄉"}
else if (zipcode==="884"){return "澎湖縣 白沙鄉"}
else if (zipcode==="885"){return "澎湖縣 湖西鄉"}
else if (zipcode==="900"){return "屏東縣 屏東市"}
else if (zipcode==="901"){return "屏東縣 三地門鄉"}
else if (zipcode==="902"){return "屏東縣 霧臺鄉"}
else if (zipcode==="903"){return "屏東縣 瑪家鄉"}
else if (zipcode==="904"){return "屏東縣 九如鄉"}
else if (zipcode==="905"){return "屏東縣 里港鄉"}
else if (zipcode==="906"){return "屏東縣 高樹鄉"}
else if (zipcode==="907"){return "屏東縣 鹽埔鄉"}
else if (zipcode==="908"){return "屏東縣 長治鄉"}
else if (zipcode==="909"){return "屏東縣 麟洛鄉"}
else if (zipcode==="911"){return "屏東縣 竹田鄉"}
else if (zipcode==="912"){return "屏東縣 內埔鄉"}
else if (zipcode==="913"){return "屏東縣 萬丹鄉"}
else if (zipcode==="920"){return "屏東縣 潮州鎮"}
else if (zipcode==="921"){return "屏東縣 泰武鄉"}
else if (zipcode==="922"){return "屏東縣 來義鄉"}
else if (zipcode==="923"){return "屏東縣 萬巒鄉"}
else if (zipcode==="924"){return "屏東縣 崁頂鄉"}
else if (zipcode==="925"){return "屏東縣 新埤鄉"}
else if (zipcode==="926"){return "屏東縣 南州鄉"}
else if (zipcode==="927"){return "屏東縣 林邊鄉"}
else if (zipcode==="928"){return "屏東縣 東港鎮"}
else if (zipcode==="929"){return "屏東縣 琉球鄉"}
else if (zipcode==="931"){return "屏東縣 佳冬鄉"}
else if (zipcode==="932"){return "屏東縣 新園鄉"}
else if (zipcode==="940"){return "屏東縣 枋寮鄉"}
else if (zipcode==="941"){return "屏東縣 枋山鄉"}
else if (zipcode==="942"){return "屏東縣 春日鄉"}
else if (zipcode==="943"){return "屏東縣 獅子鄉"}
else if (zipcode==="944"){return "屏東縣 車城鄉"}
else if (zipcode==="945"){return "屏東縣 牡丹鎮"}
else if (zipcode==="946"){return "屏東縣 恆春鄉"}
else if (zipcode==="947"){return "屏東縣 滿州鄉"}

else if (zipcode==="950"){return "臺東縣 臺東市"}
else if (zipcode==="951"){return "臺東縣 綠島鄉"}
else if (zipcode==="952"){return "臺東縣 蘭嶼鄉"}
else if (zipcode==="953"){return "臺東縣 延平鄉"}
else if (zipcode==="954"){return "臺東縣 卑南鄉"}
else if (zipcode==="955"){return "臺東縣 鹿野鄉"}
else if (zipcode==="956"){return "臺東縣 關山鎮"}
else if (zipcode==="957"){return "臺東縣 海端鄉"}
else if (zipcode==="958"){return "臺東縣 池上鄉"}
else if (zipcode==="959"){return "臺東縣 東河鄉"}
else if (zipcode==="961"){return "臺東縣 成功鎮"}
else if (zipcode==="962"){return "臺東縣 長濱鄉"}
else if (zipcode==="963"){return "臺東縣 太麻里鄉"}
else if (zipcode==="964"){return "臺東縣 金峰鄉"}
else if (zipcode==="965"){return "臺東縣 大武鄉"}
else if (zipcode==="966"){return "臺東縣 達仁鄉"}
		
else if (zipcode==="970"){return "花蓮縣 花蓮市"}
else if (zipcode==="971"){return "花蓮縣 新城鄉"}
else if (zipcode==="972"){return "花蓮縣 秀林鄉"}
else if (zipcode==="973"){return "花蓮縣 吉安鄉"}
else if (zipcode==="974"){return "花蓮縣 壽豐鄉"}
else if (zipcode==="975"){return "花蓮縣 鳳林鎮"}
else if (zipcode==="976"){return "花蓮縣 光復鄉"}
else if (zipcode==="977"){return "花蓮縣 豐濱鄉"}
else if (zipcode==="978"){return "花蓮縣 瑞穗鄉"}
else if (zipcode==="979"){return "花蓮縣 萬榮鄉"}
else if (zipcode==="981"){return "花蓮縣 玉里鎮"}
else if (zipcode==="982"){return "花蓮縣 卓溪鄉"}
else if (zipcode==="983"){return "花蓮縣 富里鄉"}
		
else if (zipcode==="890"){return "金門縣 金沙鎮"}
else if (zipcode==="891"){return "金門縣 金湖鎮"}
else if (zipcode==="892"){return "金門縣 金寧鎮"}
else if (zipcode==="893"){return "金門縣 金城鎮"}
else if (zipcode==="894"){return "金門縣 烈嶼鄉"}
else if (zipcode==="896"){return "金門縣 烏坵鄉"}
		
else if (zipcode==="209"){return "連江縣 南竿鄉"}
else if (zipcode==="210"){return "連江縣 北竿鄉"}
else if (zipcode==="211"){return "連江縣 莒光鄉"}
else if (zipcode==="212"){return "連江縣 東引鄉"}
else{return "查詢發生錯誤"}
}}